language: node_js
node_js:
  - "10"

cache:
  bundler: true
  pip: true
  directories:
    - node_modules
    - .vendor
    - /home/travis/.rvm/
    - /home/travis/.nvm/

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_install:
- sudo apt-get update
- sudo apt-get install curl
- rvm install 2.5.0
- bundle install --path="./.vendor/bundle" --jobs 3
- bundle exec rake config:bootstrap

install:
- gatsby --version

env:
  global:
    secure: pg0cuGArjQzHRZ0rqMrkGjI9yTlfyKJ7gRBKh4WtswZJxhFc3VC6PgzNPP/QGG7+OJLx99bwbh8+bg60guLmnzyzBjxNvkVFSYig+7MbzSBgH1fIin0hLJ2zWZPnW8VjNTk7WYc7LHGoYQ2SV3A9gPKcyyEGtiYQaBzcD/PdTyc=

before_script:
- bundle exec rake config:environment

script:
- bundle exec rake build:test
- bundle exec danger

after_success:
- bundle exec rake deploy:travis
