language: node_js

sudo: required
services:
  - docker

cache:
  bundler: true
  pip: true

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_install:
  - sudo docker pull jojomi/hugo
  - rvm install 2.5.0
  - bundle install --path="./.vendor/bundle" --jobs 3

script:
  - bundle exec rake build:test
  - bundle exec danger

install:
- docker run --rm jojomi/hugo hugo version

env:
  global:
    secure: pg0cuGArjQzHRZ0rqMrkGjI9yTlfyKJ7gRBKh4WtswZJxhFc3VC6PgzNPP/QGG7+OJLx99bwbh8+bg60guLmnzyzBjxNvkVFSYig+7MbzSBgH1fIin0hLJ2zWZPnW8VjNTk7WYc7LHGoYQ2SV3A9gPKcyyEGtiYQaBzcD/PdTyc=

before_script:
  - bundle exec rake config:environment

after_success:
- bundle exec rake deploy:travis