language: node_js

cache:
  - bundler
  - pip

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_install:
- rvm install 2.2
- bundle install --path="./.vendor/bundle"
- bundle exec rake config:bootstrap

install:
- hexo --version

git:
  submodules: false

env:
  global:
    secure: pg0cuGArjQzHRZ0rqMrkGjI9yTlfyKJ7gRBKh4WtswZJxhFc3VC6PgzNPP/QGG7+OJLx99bwbh8+bg60guLmnzyzBjxNvkVFSYig+7MbzSBgH1fIin0hLJ2zWZPnW8VjNTk7WYc7LHGoYQ2SV3A9gPKcyyEGtiYQaBzcD/PdTyc=

before_script:
- bundle exec rake config:environment

script:
- bundle exec rake build:test
- bundle exec danger

after_success:
- bundle exec rake deploy:travis
