language: node_js

services:
  - docker

cache:
  bundler: true
  pip: true
  directories:
    - .vendor
    - /home/travis/.rvm/
    - /home/travis/.nvm/

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_install:
  - docker pull jojomi/hugo
  - rvm install 2.5.0
  - bundle install --path="./.vendor/bundle" --jobs 3

script:
  - bundle exec rake build:test
  - bundle exec danger
  - make build

install:
- docker run --rm jojomi/hugo hugo version

env:
  global:
    secure: pg0cuGArjQzHRZ0rqMrkGjI9yTlfyKJ7gRBKh4WtswZJxhFc3VC6PgzNPP/QGG7+OJLx99bwbh8+bg60guLmnzyzBjxNvkVFSYig+7MbzSBgH1fIin0hLJ2zWZPnW8VjNTk7WYc7LHGoYQ2SV3A9gPKcyyEGtiYQaBzcD/PdTyc=

before_script:
- bundle exec rake config:environment

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GH_DEPLOY_TOKEN
  target_branch: master
  local_dir: site/public
  on:
    branch: source