language: node_js
branches:
  only:
  - source
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- npm -g install npm@latest
- npm install -g hexo
- npm install
install:
- hexo generate
git:
  submodules: false
env:
  global:
    secure: pg0cuGArjQzHRZ0rqMrkGjI9yTlfyKJ7gRBKh4WtswZJxhFc3VC6PgzNPP/QGG7+OJLx99bwbh8+bg60guLmnzyzBjxNvkVFSYig+7MbzSBgH1fIin0hLJ2zWZPnW8VjNTk7WYc7LHGoYQ2SV3A9gPKcyyEGtiYQaBzcD/PdTyc=
before_script:
- git config --global user.name 'Esteban Torres via Travis CI'
- git config --global user.email 'me@estebantorr.es'
- sed -i'' "s~git@github.com:esttorhe/esttorhe.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/esttorhe/esttorhe.github.io.git~" _config.yml
script:
- hexo deploy --silent
