baseURL = "https://estebantorr.es/"
languageCode = "en"
defaultContentLanguage = "en"
title = "The mind of Esteban"
theme = "KeepIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  post = "/:year/:month/:title/"

[params]
  since = 2014
  author= "Esteban Torres"
  subtitle = "From iOS Engineer to Engineering Manager"

  avatar = "/assets/images/avatar.png"
  socialShare = true

  description = "Mostly engineering musings from the mind of a Costarrican who transplanted to Berlin."
  keywords = "ios, ios Engineering, engineering management"

[params.gravatar]
    #email = "me+blog@estebantorr.es"   #uncomment and insert your email address to use gravatar

[params.social]
  GitHub = "esttorhe"
  Mastodon = "https://mastodon.social/@esttorhe"
  Email = "me+blog@estebantorr.es"
  Linkedin = "estebantorres"
  Telegram = "esttorhe"
  Keybase = "esttorhe"
  Reddit = "esttorhe"
  Spotify = "1268956389"
  Goodreads = "6006262-esteban"
  Lastfm = "esttorhe"
  RSS = "https://estebantorr.es/index.xml"
  Twitter = "esttorhe"

[params.share]
Twitter = true
Reddit = true
HackerNews = true
Linkedin = true

customCss = ["assets/css/terminal.css", "assets/css/cv.css"]
custom_css = ["assets/css/blockquote.css"]

[author]
  name = "Esteban Torres"

  [params.publisher]
    name = "Esteban Torres"

    [params.publisher.logo]
      url = "/assets/images/avatar.png"
      width = 40
      height = 40
    
  [params.logo]
    url = "/assets/images/avatar.png"
    width = 40
    height = 40

  [params.image]
    url = "/assets/images/cover.jpg"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 3
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/" 

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "archive"
  url = "/blog/"

[[menu.main]]
  name = "Categories"
  weight = 2.2
  identifier = "categories"
  url = "/categories/"

[[menu.main]]
  name = "Tags"
  weight = 2.5
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 4
  url = "/about"

  [[menu.main]]
  name = "Talks"
  weight = 3
  identifier = "talks"
  url = "/talks/"

  [[menu.main]]
  name = "CV"
  weight = 5
  identifier = "cv"
  url = "/cv"

[params.utterance]          # utteranc.es app - https://utteranc.es/
    owner = "esttorhe"              # Your GitHub ID
    repo = "esttorhe.github.io"               # The repo to store comments
    label = "Comments"
    issueTerm = "title"
    theme = "icy-dark"